# Generated by Django 4.1.7 on 2023-03-02 22:06

from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_altruist_enabled_alter_altruist_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altruist',
            name='url',
            field=models.CharField(max_length=200, validators=[manager.models.validate_url]),
        ),
        migrations.CreateModel(
            name='AltruistServingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(auto_now=True)),
                ('altruist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.altruist')),
                ('chain_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.chain')),
            ],
        ),
    ]
