# Generated by Django 4.1.7 on 2023-03-02 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_altruist_url_altruistservinglog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altruistservinglog',
            name='chain_id',
        ),
    ]
