# Generated by Django 4.1.7 on 2023-03-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_altruistservinglog_chain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='altruistservinglog',
            name='chain_id',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
